public voting
vocdoni/ui-scaffold pull request #465
Opened 2023-12-20 10:03 UTC by gerouvi

- added STATE and SCHEUDLE labels
-Reduced header right side
- Reduced election description line height

refs #450

2023-12-20 13:07 UTC, elboletaire requested changes
Overall looks good, but we have a link pointing nowhere that we should update first. Also, please review the Aside component links, since there they have a contrast problem

![imatge](https://github.com/vocdoni/ui-scaffold/assets/153305/310f6771-9c10-43c5-955d-8396b6eb0f7a)

2023-12-20 13:07 UTC, elboletaire commented on src/components/Organization/View.tsx
> +                          customLink: <Link href='#' target='_blank' />,
We should properly set this link here @jpaulet

2024-01-03 11:46 UTC, jpaulet requested changes
The `No description provided` is shown when there's description.

2024-01-03 14:51 UTC, elboletaire approved these changes

2024-01-03 14:52 UTC, merged