rounded census
vocdoni/ui-scaffold pull request #527
Opened 2024-01-31 12:25 UTC by gerouvi

- when advanced settings anonymous is true show disclaimer text
- show anonymous census blance accuracy in preview

2024-01-31 16:47 UTC, elboletaire requested changes
Found some typos, but also... I'm not convinced in the way this is being displayed @jpaulet.

I would not add the disclaimer here:
![imatge](https://github.com/vocdoni/ui-scaffold/assets/153305/a69dcd4f-0652-4645-bcb1-a6648b15a858)

But here makes a lot of sense, and it isn't added there:
![imatge](https://github.com/vocdoni/ui-scaffold/assets/153305/f820ce01-6569-4c3f-a9e4-a5dad662e82e)

2024-02-01 12:16 UTC, jpaulet commented
> Found some typos, but also... I'm not convinced in the way this is being displayed @jpaulet.
> 
> I would not add the disclaimer here: ![imatge](https://private-user-images.githubusercontent.com/153305/301240182-a69dcd4f-0652-4645-bcb1-a6648b15a858.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY3ODU3NzEsIm5iZiI6MTcwNjc4NTQ3MSwicGF0aCI6Ii8xNTMzMDUvMzAxMjQwMTgyLWE2OWRjZDRmLTA2NTItNDY0NS1iY2IxLWE2NjQ4YjE1YTg1OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwMVQxMTA0MzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NjFmYTY1ZGZlYjhhYzA4ZGJkNDg0N2VkNTJhY2RhZjg2YjJiYjYxNzc5N2I1MTg4YmE5OTJlYTkxMDNmNWRiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.3XPSb6rGhnlVa5cik_pIZRMKxVas_DNjsRtE7lZExjY)
> 
> But here makes a lot of sense, and it isn't added there: ![imatge](https://private-user-images.githubusercontent.com/153305/301240325-f820ce01-6569-4c3f-a9e4-a5dad662e82e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY3ODU3NzEsIm5iZiI6MTcwNjc4NTQ3MSwicGF0aCI6Ii8xNTMzMDUvMzAxMjQwMzI1LWY4MjBjZTAxLTY1NjktNGMzZi1hOWU0LWE1ZGFkNjYyZTgyZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwMVQxMTA0MzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wOWQyYmJjMzg2MDg5YmFmNzQwNzc1MThjNTQ4ZTAwOWJiZDkwNzE1ZGRlNTAxZmI4ZWZjNjk2MjQ2N2U1NzkwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.q7RTAr58TzLmvLya8rGceIFzTdN-qsWrqLFu56savw0)

You are right, @gerouvi can you move this text to the "census" step. Use the default Chakra component for "Info Alert", place it here: 
![image](https://github.com/vocdoni/ui-scaffold/assets/6894329/7a04cbe4-f287-4ac2-b669-5dd1c2c53b58)

With the text: `This voting system utilizes token-based voting power (public on-chain). As you selected the "Anonymous voting" option, weights will be grouped into similar balances and rounded down. This sacrifices some accuracy but preserves anonymous identity by unlinking balances from wallets.`

It will only appear if "anonymous voting" option was selected in the first step.

2024-02-02 10:06 UTC, elboletaire requested changes

2024-02-02 10:06 UTC, elboletaire commented on src/i18n/locales/ca.json
> +      "legal_disclaimer": "Aquest sistema de votació utilitza el poder de votació basat en tokens (públic a la cadena de blocs). Com heu seleccionat l'opció de 'Votació anònima', els pesos es grupara
Should be "s'agruparan" and "i s'arrodoniran"

2024-02-02 12:57 UTC, elboletaire approved these changes

2024-02-02 12:57 UTC, merged