pro plan options
vocdoni/ui-scaffold pull request #555
Opened 2024-02-20 10:55 UTC by gerouvi

Added the options of the Pro Plan with the modal to send an email requiring them or scheduling an appointment

2024-02-21 17:42 UTC, elboletaire requested changes
I'll continue reviewing tomorrow...

2024-02-21 17:42 UTC, elboletaire commented on .env.example
> +FEATURES='{"faucet":true,"vote":{"anonymous":true,"overwrite":true,"secret":true,"customization":true},"types":["single":true,"multi":true,"approval":true,"participatory":true,"borda":true],"login":[
You used an array to define an object in types.

2024-02-23 16:08 UTC, jpaulet approved these changes

2024-02-28 13:35 UTC, elboletaire requested changes
A part from the code changes in the review, there are some other visual things that should be addressed:

![imatge](https://github.com/vocdoni/ui-scaffold/assets/153305/d2a4224f-b9d7-4110-867c-36d27258c801)
These should not be overlapping with the census manager.

Probably related to the wrong features initialization, disabling features does not seem to be working:
![imatge](https://github.com/vocdoni/ui-scaffold/assets/153305/19ef2734-a22f-43f7-9643-59d0ca235232)
This is the rendered component after setting `FEATURES='{"voting":["single"]}'`

2024-02-28 13:35 UTC, elboletaire commented on vite.config.ts
> +  let vocdoniEnvironment = process.env.VOCDONI_EºNVIRONMENT
What the actual...

2024-02-28 13:35 UTC, elboletaire commented on src/importmeta.d.ts
> +      }
I don't see these in features.ts, and they should be defined there, like it's done with `_census`.

2024-03-16 11:40 UTC, jpaulet commented
This branch needs a full review: the "onvote" theme is not working properly, and in the default one, there are some issues. Let's talk about it next week.

2024-03-18 09:25 UTC, jpaulet commented
Change the link to book a meeting to: [](https://calendly.com/vocdoni-app/30min)

2024-03-19 11:23 UTC, elboletaire commented
@gerouvi remember to update this branch with develop one, otherwise this cannot be merged.

2024-03-21 18:57 UTC, jpaulet commented
When trying to send a mail, this error appears: 
![image](https://github.com/vocdoni/ui-scaffold/assets/6894329/a2886ed8-5dbe-45a9-b6ba-8f5b47490596)

2024-03-26 13:39 UTC, elboletaire requested changes

2024-03-26 13:39 UTC, elboletaire commented on .env.example
> +FEATURES='{"faucet":true,"vote":{"anonymous":true,"overwrite":true,"secret":true,"customization":true},"types":{"single":true,"multi":true,"approval":true,"participatory":true,"borda":true},"login":[
This example does not match with the actual implementation.

2024-03-26 13:39 UTC, elboletaire commented on vite/features.ts
> +    if (!unimplemented_voting_type.includes(el)) throw new Error('Unimplemented voting type ' + el + ' does not exist')
Try to use template strings for these errors.

2024-04-02 10:48 UTC, elboletaire commented on .env.example
> +FEATURES='{"faucet":true,"vote":{"anonymous":true,"overwrite":true,"secret":true,"customization":true},"types":{"single":true,"multi":true,"approval":true,"participatory":true,"borda":true},"login":[
@gerouvi I still miss the `unimplemented_voting_types`, `unimplemented_census` and `voting_types` in that FEATURES env 🤔

2024-04-02 14:14 UTC, elboletaire commented on src/components/ProcessCreate/Steps/Census.tsx
> +  const [showProCards, setShowProCards] = useState(false)
No need to change it but as a FYI: for this kind of usage you can use the chakra-ui `useDisclosure` hook (used a few lines above actually). Simply rename the vars used to others and that's it.

2024-04-02 16:03 UTC, elboletaire approved these changes

2024-04-02 16:04 UTC, merged