New landing revamp
vocdoni/ui-scaffold pull request #657
Opened 2024-04-18 09:17 UTC by jpaulet

Improved landing page by:

- Added new images
- Improved texts
- Increased and unified font-size
- Added "basier" font and font-family
- Added new layout in Benefits, Features, Clients and Contact-us
- Added background image
- Modified clients icons and removed "Pirates"
- Added new styles and some background textures & figures
- Unified margins and paddings between sections
- Other minor improvements and unifications

2024-04-29 10:16 UTC, elboletaire requested changes
Other than the issue with the logo background, I'm not sure I like the buttons having an underline text, which is only seen here in the landing.

![imatge](https://github.com/vocdoni/ui-scaffold/assets/153305/0b764707-b193-4ebe-b09d-0558cbcb9fdc)

2024-04-29 10:16 UTC, elboletaire commented on public/default/assets/decidim.png
Even though the background is transparent, it may have a thin layer of gray color, because it shows gray in the final result:

![imatge](https://github.com/vocdoni/ui-scaffold/assets/153305/4b75dc9b-aea6-4a7a-bf9d-2ec8313615ec)

2024-05-02 09:38 UTC, jpaulet commented on public/default/assets/decidim.png
It's ok. I will upload a new one later if necessary.

2024-05-02 09:43 UTC, jpaulet commented on public/default/assets/decidim.png
Also, the button with underline is to give more emphasis to the CTA. Go ahead. 

I will review it in the next iterations but this shouldn't block the merge.

2024-05-02 10:03 UTC, elboletaire approved these changes

2024-05-02 10:03 UTC, merged