F/calculator
vocdoni/ui-scaffold pull request #673
Opened 2024-05-02 09:30 UTC by gerouvi

Election cost calculator

2024-05-16 09:56 UTC, jpaulet commented
Missing translations and we should select, by default, the "Single choice" voting, instead of none: 
![image](https://github.com/vocdoni/ui-scaffold/assets/6894329/22326c17-5f49-4fe0-870c-61577b0627bc)

2024-06-18 10:24 UTC, elboletaire requested changes
This section is missing the final dot on sentences (in all languages). Also, add more padding in-between the sentences.
![imatge](https://github.com/vocdoni/ui-scaffold/assets/153305/a849e0c5-9b81-4822-a818-83c41cbf3cc8)

Also, we should add a new env var for this payment gateway (not sure if the stripe part can be toggled via env var @emmdim, but if it requires env vars it should be disabled when no env vars are set, and only allow crypto payments)

2024-06-18 10:24 UTC, elboletaire commented on src/i18n/locales/ca.json
> +    "recurring_description": "<p>Necessites una quantitat recurrent de tokens o tens la intenció de crear múltiples eleccions?<p/><p>Necessites votació digital segura pel teu software?</p><p>Oferim i
Missing dot after `necessitats`.

2024-06-19 06:58 UTC, elboletaire approved these changes

2024-06-19 06:59 UTC, elboletaire requested changes
I approved it because looks good, but prettier complains about something wrong in these new files.

2024-06-19 08:34 UTC, emmdim commented
> I approved it because looks good, but prettier complains about something wrong in these new files.

Prettier issues fixed

2024-06-19 10:42 UTC, elboletaire commented on vite.config.ts
> +  let stripePublicKey = process.env.STRIPE_PUBLIC_KEY || ''
No need to to this here (do it directly in the JSON.stringify part), plus there's no need for a `let`. A `const` would be better.

2024-06-25 14:33 UTC, jpaulet commented
- [ ] When the "Calculate Cost" button is clicked, if the open tab is different than the "One-time", switch to this tab automatically.
- [ ] The "Min. 100 tokens" and "Coming soon" texts should be smaller.
- [ ] In the "If you have any question, check our FAQ or contact our support team" the "contact" word should be a link to "https://www.vocdoni.io/contact". 
- [ ] Change CA text from: "Si tens alguna pregunta, consulta les nostres Preguntes Freqüents o posa't en contacte amb el nostre equip de suport" to: "Si tens algun dubte, consulta les FAQ o posa't en contacte amb l'equip de suport". 
- [ ] Change ES text from: "Si tienes alguna pregunta, consulta nuestras preguntas frecuentes o contacta con nuestro equipo de soporte" to "Si tienes alguna duda, consulta las FAQ o contacta con el equipo de soporte".
- [ ] In the previous 2 tasks, add a anchor in the landing page to the FAQ section and link it with the word "FAQ" in all languages ( https://app.vocdoni.io/#faq )
- [ ] Move the 3 buttons used to switch between tabs outside the main container, in the top and as secondary buttons.
- [ ]  If the user is not logged-in and clicks the "Buy Tokens" button, show the login modal instead of the new blank page: 
![image](https://github.com/vocdoni/ui-scaffold/assets/6894329/003e6ebc-f414-4fca-8906-1c5070d1fb55)

- [ ]  Change the text: 

**How Vocdoni Works**

Vocdoni uses its own public voting blockchain (Vochain) to ensure maximum security, end-to-end verifiability, and a censorship-resistant voting process. To use this infrastructure, users need to expend tokens (a credit representation of the usage of the Vochain) to create the necessary election. Various parameters, such as census size and duration, determine the final voting cost.

Here you can simulate the cost of your voting process and purchase the needed tokens.

2024-06-27 08:23 UTC, elboletaire commented
IMHO the total should be shown always, otherwise selecting anything outside of "Once" will render the left side useless

![imatge](https://github.com/vocdoni/ui-scaffold/assets/153305/9f769686-f529-4a1e-b686-e6a69ce8d530)

2024-07-19 14:34 UTC, jpaulet commented
- [ ] The encrypted/overwrite flags are not working.
- [ ] If the cost is less than 100 tokens, do not disable the button. The purchase should still be possible, but for 100 tokens (even if only 45 are needed).
- [ ] In the "% Packages" tab, the different packages are not correctly sent to Stripe, and the amount always appears as "100".
- [ ] If an attempt is made to purchase more than 9999 tokens, the Stripe page crashes with the following error:

error 'session.New: {"status":400,"message":"If adjustable quantity is enabled, line_items[0][adjustable_quantity][maximum] (10000) must be greater than or equal to line_items[0][quantity] (16853). line_items[0][adjustable_quantity][maximum] can be set as high as 999999, but defaults to 99 if not set.","param":"line_items[0][quantity]","request_id":"req_8GVQ6c7WCTOIgY","request_log_url":"https://dashboard.stripe.com/test/logs/req_8GVQ6c7WCTOIgY?t=1721397251","type":"invalid_request_error"}'

- [ ] Remove/hide (for now) the text `A confirmation email will be sent to ...` until we actually send the email.
- [ ] If the user rejects to sign, the text should be: 

> You aborted the action. Without signing, you will not receive the purchased tokens. If this was an error, you can click on "Sign" to continue with the operation. If you want a refund, click on the "Refund" button.

- [ ] The "Get more" (tokens) button in the profile dropdown, should point to the calculator instead of the faucet.
- [ ] Add more vertical space between the header and the Stripe component.

2024-07-30 10:39 UTC, elboletaire requested changes

2024-07-30 10:39 UTC, elboletaire commented on src/components/Calculator/index.tsx
> +const MINIMUM_PURCHASE_TOKENS = 100
Define these in constants, following the constants naming we have there.

2024-07-30 10:39 UTC, elboletaire commented on src/components/Calculator/index.tsx
> +            }}
Wut? Why not simply...
```suggestion
            onChange={(e) => {
              setTotalTokens(Number(e))
            }}
```

2024-07-30 10:39 UTC, elboletaire commented on src/components/Calculator/index.tsx
> +  const stripeEnabled = import.meta.env.STRIPE_PUBLIC_KEY.length > 0
Better have it in constants too.

2024-07-30 10:39 UTC, elboletaire commented on src/components/Faucet/Stripe.tsx
> +      }
Always specify the radix
```suggestion
      if (amount && !isNaN(parseInt(amount, 10))) {
        uri = `${uri}/${amount}`
      }
```

2024-07-30 10:39 UTC, elboletaire commented on src/components/Faucet/Stripe.tsx
> +  }, [])
Kinda cumbersome to define a method that returns stuff and then use that return to set state values. Why not simply set state values during he function execution?

Also, why the infinite loop checking for a state value that won't be on the first run for sure??

2024-07-30 10:39 UTC, elboletaire commented on src/components/Faucet/Stripe.tsx
> +      `0x${account?.address}` !== recipient.toLowerCase()
Use `ensure0x` rather than manually forcing the prefix

2024-07-30 10:39 UTC, elboletaire commented on src/components/Faucet/Stripe.tsx
> +            customLink: <Link href='mailto:orders@vocdoni.org' />,
do no name it `customLink`. Name it `mailto` in this case.

2024-07-30 10:39 UTC, elboletaire commented on src/elements/Stripe.tsx
> +    </Box>
These extra surrounding boxes look weird. Considering you're adding them on each view, and that these are routing elements, wouldn't make more sense to have such Box defined in the layout?

2024-07-30 10:39 UTC, elboletaire commented on src/elements/Stripe.tsx
> +    </Box>
Same, probably non-required wrapper.

2024-07-30 10:39 UTC, elboletaire commented on src/themes/default/components/Home/index.tsx
> +  }, [hash])
Add a comment to the use effect to know its behavior.

2024-07-30 10:39 UTC, elboletaire commented on src/themes/onvote/index.ts
> +      },
You should avoid using classes unless you don't have other options. In this case you should have defined a custom style object, like with any other custom component: https://v2.chakra-ui.com/docs/styled-system/component-style#styling-single-part-components

2024-07-30 10:39 UTC, elboletaire commented on vite/features.ts
> -  console.log('features:', features)
WHY? Get it back please. Change it to console.info if you feel better about it, but that console has to be there.

2024-08-02 15:09 UTC, merged