Change document title
vocdoni/ui-scaffold pull request #697
Opened 2024-05-21 08:42 UTC by selankon

It changes the document title on certain pages using the `useDocumentTitle` hook.

When the hook is unmounted it goes back to the default page title

2024-05-23 15:15 UTC, elboletaire approved these changes

2024-05-23 15:16 UTC, elboletaire commented on src/elements/Process.tsx
> +        <SetProcess />
Terrible name 😅

2024-06-12 09:44 UTC, selankon commented on src/elements/Process.tsx
> +        <SetProcess />
True! 🙈 dbf3e00

2024-06-12 11:53 UTC, elboletaire requested changes
I see a problem here... navigating through pages maintains one of the first titles set (?)

To reproduce:
- Go to your organization, you'll se the title change
- Go to the home page, the title remains with the org name

2024-06-17 09:54 UTC, selankon commented
FTR if we would like to centraliza all on an only one hook/component that just change the title, and dinamically check if is inside an election context or organization context to set the title, i did this approach which is not finished but can be used as inspiration if we need to do it on the future

```ts
export function useDocumentTitle(title?: string) {
  const defaultTitleRef = useRef(document.title)
  const electionCtx = useContext(ElectionContext)
  const orgCtx = useContext(OrganizationContext)

  useEffect(() => {
    const isOnvote = import.meta.env.theme === 'onvote'
    let prepend = 'Vocdoni'
    // Vocdoni - The voice of digital voting
    // Anonymous Gasless and Modular voting for Web3
    let title = 'The voice of digital voting'
    if (isOnvote) {
      title = defaultTitleRef.current
      prepend = 'OnVote'
    }
    if (electionCtx && electionCtx.election instanceof PublishedElection) {
      title = electionCtx.election?.title.default
    } else if (orgCtx && orgCtx.organization) {
      title = orgCtx.organization?.account.name.default ?? orgCtx.organization?.address ?? ''
    }

    document.title = `${prepend} - ${title}`
    return () => {
      document.title = defaultTitleRef.current
    }
  }, [electionCtx, orgCtx, title])
}
```

2024-06-18 07:44 UTC, elboletaire commented
> I see a problem here... navigating through pages maintains one of the first titles set (?)
> 
> To reproduce:
> 
>     * Go to your organization, you'll se the title change
> 
>     * Access a process, the title changes again
> 
>     * Go to the home page, the title remains with the election name (?)

I can still reproduce this 😕

2024-06-25 16:16 UTC, elboletaire approved these changes

2024-06-25 16:17 UTC, merged