terms and privacy
vocdoni/ui-scaffold pull request #736
Opened 2024-07-15 09:27 UTC by gerouvi

New terms and privacy

2024-07-15 11:05 UTC, elboletaire requested changes

2024-07-15 11:05 UTC, elboletaire commented on src/themes/default/components/Footer.tsx
> +              link2: <Link href='/privacy' color='gray' />,
Should be a router link and use `to`.

2024-07-15 11:05 UTC, elboletaire commented on src/components/TermsAndPrivacy/Terms.tsx
> +  return (
Friendly reminder you can simplify this to:

```tsx
const Terms = () => (
)
```

2024-07-15 11:05 UTC, elboletaire commented on src/components/TermsAndPrivacy/Privacy.tsx
> +  return (
Same as in terms. No need to use `{ return` when there's no logic in the component.

2024-07-15 13:43 UTC, elboletaire commented
@jpaulet I do now realize the onvote theme does not have the terms and conditions links visible until you login (?) 😕

2024-07-15 14:01 UTC, gerouvi commented
> @jpaulet I do now realize the onvote theme does not have the terms and conditions links visible until you login (?) 😕

We could also put it in the footer, right?

2024-07-15 17:15 UTC, jpaulet commented
Yes, let's add it to the footer in the Onvote app.

2024-07-16 08:42 UTC, elboletaire approved these changes

2024-07-16 08:43 UTC, elboletaire commented
Aren't we translating these pages?

2024-07-16 08:45 UTC, merged