removed unnecessary variants
vocdoni/ui-scaffold pull request #764
Opened 2024-09-13 08:39 UTC by gerouvi

Removed unnecessary variants in inputs and text area, and I moved the styles from the auth variant to baseStyles so that all inputs/text areas have the same styles. If we need different styles in the future, we will create a variant.

2024-09-13 08:50 UTC, jpaulet approved these changes

2024-09-16 08:46 UTC, selankon requested changes

2024-09-16 08:46 UTC, selankon commented on src/components/AccountSaas/Create.tsx
> +              variant='ss'
Variant ss??

2024-09-16 08:46 UTC, selankon commented on src/components/Auth/SignUp.tsx
> +              <Input {...register('lastName', { required })} type='text' placeholder='Last Name' />
placeholders should be translated using `t` function

2024-09-16 09:33 UTC, selankon requested changes

2024-09-16 09:33 UTC, selankon commented on src/components/Auth/SignUp.tsx
> +              <Input {...register('firstName', { required })} type='text' placeholder='First Name' />
This placeholder is still without translation :S

2024-09-16 09:43 UTC, selankon requested changes

2024-09-16 09:43 UTC, selankon commented on src/components/AccountSaas/Create.tsx
>                placeholder={t('form.account_create.description_placeholder').toString()}
Unnecessary tostring

2024-09-16 09:55 UTC, selankon approved these changes

2024-09-16 09:56 UTC, merged