create process form styles
vocdoni/ui-scaffold pull request #781
Opened 2024-10-07 09:28 UTC by gerouvi

The styles from the SAAS process are applied, creating their different variations based on the default theme.

2024-10-14 09:23 UTC, selankon requested changes
Good job, this PR is huge! Try to find the way to do not rely on the `import.meta.env.SAAS_URL` to check if use styles for saas theme

2024-10-14 09:23 UTC, selankon commented on src/elements/LayoutProcessCreate.tsx
> +              {isSaas && <DarkModeToggle />}
Theme not SAAS_URL

2024-10-14 09:23 UTC, selankon commented on src/router/SaasProtectedRoutes.tsx
> +  return <Outlet />
I think you forgot to delete this :)

2024-10-14 09:23 UTC, selankon commented on src/themes/saas/index.ts
> +import { Form } from './components/form'
Some imports of this file are not well imported and rise lint issues.

2024-10-18 07:25 UTC, elboletaire requested changes
Looks quite good, but there are a few things about the final result (which are hard to pinpoint directly in the code):
- The process creation had the option to create both multi-question and single-type questions, but with these changes, the single-type no longer works. Please try to restore it.
- I’m not a fan of adding buttons and features that aren’t immediately implemented. This applies to both the "approval" option added and all the new election options.
- Speaking of that new election options section that was added, I find it quite lacking. At the very least, it should have a title. And if the options haven’t been implemented yet, it might be a good idea to set all the unimplemented options as disabled until they’re properly developed (since I understand you added them for theming purposes and want to preview them).
- The use of color variables is quite wrong if the idea was to continue using themes... Remember, variable names for theme elements should be related to the section they belong to, rather than directly using a name like colorsBase.white.dark. But don’t worry about this—I’ll probably remove the theming system ASAP to reduce the burden it's causing on the project.

2024-10-18 07:25 UTC, elboletaire commented on src/themes/saas/components/checkbox.ts
> +// Manteniendo la estructura original
Do not add comments in languages other than English, but also... this comment looks GPT-suspicious

2024-10-21 08:59 UTC, elboletaire approved these changes

2024-10-21 08:59 UTC, merged