Dashboard menu styles
vocdoni/ui-scaffold pull request #905
Opened 2024-12-30 17:20 UTC by gerouvi

Dashboard menu active styles and fixed issues color scheme gray

2024-12-31 09:55 UTC, elboletaire requested changes

2024-12-31 09:55 UTC, elboletaire commented on src/components/Dashboard/Menu/Item.tsx
> +    isActive={hasChildren ? (isOpen ? true : false) : false} // Set active state
Why...? The logic for being or not active was done in Options, why are you redoing the logic here again? If it wasn't working as expected, should have been fixed where it was being done.

2025-01-02 21:13 UTC, gerouvi commented on src/components/Dashboard/Menu/Item.tsx
> +    isActive={hasChildren ? (isOpen ? true : false) : false} // Set active state
We discussed with @jpaulet applying different styles when an item is active, depending on whether it has children or not. In one case, a background color is used, and in the other, an underline. The problem is that I can’t filter whether it has children or not in the theme. That’s why, if it has children, I apply the styles in the theme, and if not, I apply the styles (underline) inline.

2025-01-03 16:58 UTC, elboletaire commented on src/components/Dashboard/Menu/Item.tsx
> +    isActive={hasChildren ? (isOpen ? true : false) : false} // Set active state
Ok, but it would have been better to have a variant for this, rather than hand-picking the styles. This way you only need to switch between the `transparent` and the `text` (or whatever) variant, rather than switching the `isActive` and adding inline styles.

2025-01-07 13:09 UTC, elboletaire approved these changes

2025-01-07 13:09 UTC, merged